from setuptools import find_packages, setup
import os
from glob import glob

package_name = 'bocbot_hunter'

setup(
    name=package_name,
    version='0.0.0',
    packages=find_packages(exclude=['test']),
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
        ('share/' + package_name + '/launch',
            ['launch/bocbot_hunter.launch.py',
             'launch/bocbot_hunter_gazebo.launch.py',
             'launch/simple.launch.py',
             'launch/basic.launch.py',
             'launch/test.launch.py',
             'launch/extreme.launch.py',
             'launch/wheel.launch.py',
             'launch/soccer_match.launch.py',
             'launch/manual_vs_auto.launch.py']),
        ('share/' + package_name + '/worlds',
            ['worlds/bocbot_hunter_world.world', 'worlds/arena.world']),
        ('share/' + package_name + '/urdf',
            ['urdf/bocbot.urdf.xacro', 'urdf/bocbot.gazebo']),
        ('share/' + package_name + '/media/materials/scripts',
            ['media/materials/scripts/chicken_drive.material']),
        ('share/' + package_name + '/media/materials/textures',
            ['media/materials/textures/logo_chicken_drive.png']),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='seatech',
    maintainer_email='tatayoyoh@mymail',
    description='Package for the bocbot hunter robot - ball detection, obstacle avoidance and control',
    license='Apache-2.0',
    extras_require={
        'test': [
            'pytest',
        ],
    },
    entry_points={
        'console_scripts': [
            'ball_detector = bocbot_hunter.ball_detector:main',
            'obstacle_avoidance = bocbot_hunter.obstacle_avoidance:main',
            'hunter_controller = bocbot_hunter.hunter_controller:main',
            'fake_ball_publisher = bocbot_hunter.fake_ball_publisher:main',
            'camera_viewer = bocbot_hunter.camera_viewer:main',
            'simple_hunter = bocbot_hunter.simple_hunter:main',
            'fast_hunter = bocbot_hunter.fast_hunter:main',
            'basic_mover = bocbot_hunter.basic_mover:main',
            'test_mover = bocbot_hunter.test_mover:main',
            'extreme_test = bocbot_hunter.extreme_test:main',
            'wheel_test = bocbot_hunter.wheel_test:main',
            'goal_detector = bocbot_hunter.goal_detector:main',
            'robot_uprighter = bocbot_hunter.robot_uprighter:main',
            'ball_lidar_detector = bocbot_hunter.ball_lidar_detector:main',
            'dual_pov_viewer = bocbot_hunter.dual_pov_viewer:main',
            'score_tracker = bocbot_hunter.score_tracker:main',
            'color_ring_detector = bocbot_hunter.color_ring_detector:main',
            'manual_control = bocbot_hunter.manual_control:main',
            'simple_auto_hunter = bocbot_hunter.simple_auto_hunter:main',
            'ball_position_publisher = bocbot_hunter.ball_position_publisher:main',
            'game_manager = bocbot_hunter.game_manager:main',
            'game_viewer = bocbot_hunter.game_viewer:main',
        ],
    },
)
